### ISSUE TITLE
Possible to make Stuyvesant town searchable?

### ISSUE THREAD

**Issue by mdornfe1** [danvk/sfhistory#6]
I'm told my family owned a grocery store at 535 East 17th st in 1917. As far as I can tell this address was located in what is now Stuyvesant Town. I believe Stuyvesant Town was only constructed post WWII, so the streets continued on uninterrupted. Would it be possible to make that area of NYC searchable for the the time prior to Stuyvesant Town construction?

**Comment by danvk** [comment]
Hi! I was wondering why this was filed on the OldSF repo and not the OldNYC one. Then I noticed that I linked to it on the About page! That's fixed now.

Here's the OldNYC issue that you want: https://github.com/danvk/oldnyc/issues/22

Feel free to subscribe to it for updates!
